version: 0.1.0-BUILD{build}
image: Visual Studio 2017
init: install-android-sdk.ps1 
before_build:
  - nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: normal
  project: aerogear-xamarin-sdk.sln
test: on
